### ISSUE TITLE
Ability to serve custom local branding elements at runtime 

### ISSUE THREAD

**Issue by iberdinsky-skilld** [launchrctl/web#41]
If we suppose this app be used by various people/companies we should be able to provide different levels of ui customisation.
Can be optional file web-ui.yaml with option to setup

- Logo
- Branding colors
- Fonts
etc.

**Comment by davidferlay** [comment]
I guess if dist is built beforehand and archive stored on github it won't be possible to access branding styles located in domain repositories
like
```
➜ ag machine_color_ platform/group_vars/platform/vars.yaml     
212:machine_color_1: '#ffffff' #White
213:machine_color_10: '#57f4d2' #Light green
214:machine_color_11: '#313a5e' #Darker blue/gray
215:machine_color_12: '#5039ea' #Dark blue
216:machine_color_13: '#6bd3ff' #Light blue
217:machine_color_14: '#6691ff' #Bright blue 2
218:machine_color_15: '#b366ff' #Bright purple
219:machine_color_16: '#feefa4' #Light yellow
220:machine_color_17: '#ff0000' #Bright red
221:machine_color_2: '#111832' #Navy blue
222:machine_color_3: '#4c567b' #Dark blue/gray
223:machine_color_4: '#4f4dff' #Bright blue
224:machine_color_5: '#f0f4ff' #Very light blue/gray
225:machine_color_6: '#aeb9e0' #Light blue/gray
226:machine_color_7: '#d6def5' #Lighter blue/gray
227:machine_color_8: '#fa47a1' #Pink
228:machine_color_9: '#8994be' #Mid blue/gray
```

for logo it can work in different way: svg text content can be stored in a group_var variable as well (it's the case for erp or share i think)
or group var variable can point to a file directly (that's the case for most apps)
