### ISSUE TITLE
Colors in terminal output

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/web#58]
## Current

- When user executes an action from web UI, terminal output shows logs
- Colors do not display as they do when action is run in terminal
![image](https://github.com/launchrctl/web/assets/20738264/feb10c58-de9a-4de7-af0b-3b4a2ad619f3)

## Expected

- Colors should display as expected in terminal logs

**Comment by iberdinsky-skilld** [comment]
I would better postpone it. Until we finish terminal. and them we need to add https://xtermjs.org/ or similar solution

**Comment by davidferlay** [comment]
Current result :

![image](https://github.com/launchrctl/web/assets/20738264/75c06a04-2858-4e4a-ba10-539f7172c2eb)



Still missing color in terminal though
