### ISSUE TITLE
Password/passphrase fields not masked in form

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/web#59]
## Current

- Values entered in action form fields labelled `password` or `passphrase` display in clear
![image](https://github.com/launchrctl/web/assets/20738264/0e1bcb68-a3a9-4d56-aa11-519a7183a551)

## Expected

- Values entered in action form fields labelled `password` or `passphrase` should be masked automatically, without the need of front schema definition

**Comment by iberdinsky-skilld** [comment]
This could be common UI schema. Or some mapping to generate UI-schema dynamically.
